name: CI
on:
   push:
     branches:
       - '*'         # matches every branch that doesn't contain a '/'
       - '*/*'       # matches every branch containing a single '/'
       - '**'        # matches every branch
       - '!master'   # excludes master
   pull_request:
     branches: [develop,master,pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        steps:
         - uses: actions/checkout@v3
         - name: Cache node modules #https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
           uses: actions/cache@v3
           with:
             path: Ëœ/.npm
             key: with ${{runner.os}}-node-${{ hashFiles('**/package-lock.json')}}
             restore-keys: |
                ${{ runner.os}}-node-
         - name: Use Node Js
           uses: actions/setup-node@v3
           with:
             node-version: "18.x"
         - run: npm ci
         - run: npm run  format
         - run: npm run  format:check
         - run: npm test -- --coverage
           env:
             CI: true
         - name: Upload test coverage
           uses: actions/upload-artifact@v3
           with:
            name: code-coverage
            path: coverage

         - name: Build Proy
           if: github.event_name == 'push'
           run: |
             npm run build
             npm install -g surge
             npm install -g semantic-release
         - name: Upload build folder
           if: github.event_name == 'push'
           uses: actions/upload-artifact@v3
           with:
            name: build
            path: build
         - name: zip assents
           run: |
            zip -r build.zip ./build
            zip -r coverage.zip ./coverage
         - name: Semantic release # //https://semantic-release.gitbook.io/semantic-release/usage/plugins
           if: github.event_name == 'push' && github.ref == 'refs/heads/master'
           run:  npx semantic-release
         - name: Download artifacts
           uses: actions/download-artifact@v3
         - name: Deploy to staging
           if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
           run: npx surge --project ./build --domain  silencio-apparatusos.surge.sh
         - name: Deploy to Prod
           if: github.event_name == 'push' && github.ref == 'refs/heads/master'
           run: npx surge --project ./build --domain  prodsilencio-apparatusos.surge.sh
         - name: Upload coverage reports to Codecov
           run: npx codecov
         - name: Open Issues for fails
           if: failure() && github.event_name == 'push' || github.event_name == 'pull_request'
           run: |
              curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/issues \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '{
                "title": "Automated issue for commit: ${{ github.sha }}",
                "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
                }' \
              --fail
