name: CI
on:
   push:
     branches:
       - '*'         # matches every branch that doesn't contain a '/'
       - '*/*'       # matches every branch containing a single '/'
       - '**'        # matches every branch
       - '!master'   # excludes master
   pull_request:
     branches: [develop]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
         - name: Use Node Js
           uses: actions/setup-node@v1
           with:
             node-version: "16.x"
         - run: npm ci
         - run: npm run  format:check
         - run: npm test -- --coverage
           env:
             CI: true
